# Generated by Django 4.1.7 on 2023-02-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gym_city_alter_gym_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), to='api.gym'),
        ),
    ]
