# Generated by Django 4.1.7 on 2023-02-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='Password@123456', max_length=128),
            preserve_default=False,
        ),
    ]
