# Generated by Django 4.1.7 on 2023-02-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_gym_zip_code_remove_member_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='state',
        ),
    ]
