# Generated by Django 4.1.7 on 2023-02-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
