# Generated by Django 4.1.7 on 2023-02-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_member_username_alter_member_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='my_member_table',
        ),
    ]
