# Generated by Django 4.1.7 on 2023-02-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_member_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
