# Generated by Django 4.1.7 on 2023-02-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_member_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
