# Generated by Django 4.1.7 on 2023-02-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_member_age_member_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
