# Generated by Django 4.1.7 on 2023-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_username_member_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
    ]
