# Generated by Django 4.1.7 on 2023-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_username_field_member_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=4, null=True),
        ),
    ]
