# Generated by Django 4.1.7 on 2023-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_member_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
