# Generated by Django 4.1.7 on 2023-02-17 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_member_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6, validators=[django.core.validators.MaxValueValidator(999.99), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)]),
        ),
    ]
