# Generated by Django 4.1.7 on 2023-02-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_member_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
    ]
