# Generated by Django 4.1.7 on 2023-02-21 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_member_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='target',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, validators=[django.core.validators.MaxValueValidator(999.99), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)]),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, validators=[django.core.validators.MaxValueValidator(999.99), django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)]),
        ),
    ]
