# Generated by Django 4.1.7 on 2023-03-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_admin_gym_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='admin_GYM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gym')),
            ],
        ),
    ]
