# Generated by Django 4.1.7 on 2023-03-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_gym_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=100)),
                ('gym_admin_name', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gym')),
            ],
        ),
        migrations.DeleteModel(
            name='admin_GYM',
        ),
    ]
