# Generated by Django 4.1.7 on 2023-03-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_admingym_gym_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmember',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
    ]
