# Generated by Django 4.1.7 on 2023-05-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_adminmember_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership_end_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_start_date',
        ),
    ]
