# Generated by Django 4.1.7 on 2023-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_member_membership_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gym',
        ),
        migrations.AddField(
            model_name='member',
            name='gym_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
