# Generated by Django 4.1.7 on 2023-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_member_gym_member_gym_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
