# Generated by Django 4.1.7 on 2023-05-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_member_zip_code_alter_member_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='gym_name',
            new_name='gym',
        ),
    ]
